{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "peat-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "peat-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "peat-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
